-- Migration para criar tabelas do módulo de Denúncias Comunitárias (Issues)

CREATE TABLE issues (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo          VARCHAR(150) NOT NULL,
    descricao       VARCHAR(2000) NOT NULL,
    latitude        DOUBLE PRECISION NOT NULL,
    longitude       DOUBLE PRECISION NOT NULL,
    foto_url        VARCHAR(500),
    status          VARCHAR(50) NOT NULL,
    tipo            VARCHAR(50) NOT NULL,
    data_criacao    TIMESTAMP NOT NULL,
    autor_id        BIGINT NOT NULL,
    CONSTRAINT fk_issue_autor FOREIGN KEY (autor_id) REFERENCES usuarios(id)
);

CREATE TABLE issue_interactions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo            VARCHAR(50) NOT NULL,
    conteudo        VARCHAR(1000),
    data_criacao    TIMESTAMP NOT NULL,
    issue_id        BIGINT NOT NULL,
    usuario_id      BIGINT NOT NULL,
    CONSTRAINT fk_interaction_issue FOREIGN KEY (issue_id) REFERENCES issues(id) ON DELETE CASCADE,
    CONSTRAINT fk_interaction_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

-- Índices para performance
CREATE INDEX idx_issues_tipo_status ON issues(tipo, status);
CREATE INDEX idx_issues_lat_lon ON issues(latitude, longitude);
CREATE INDEX idx_issues_autor ON issues(autor_id);
CREATE INDEX idx_interactions_issue ON issue_interactions(issue_id);
CREATE INDEX idx_interactions_usuario ON issue_interactions(usuario_id);

