CREATE TABLE atendimentos_denuncia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    denuncia_id BIGINT NOT NULL UNIQUE,
    empresa_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    descricao_planejada VARCHAR(2000) NOT NULL,
    descricao_reparo VARCHAR(2000),
    foto_depois_url VARCHAR(500),
    motivo_contestacao VARCHAR(2000),
    data_aceite TIMESTAMP NOT NULL,
    data_inicio TIMESTAMP,
    data_conclusao_empresa TIMESTAMP,
    data_confirmacao_autor TIMESTAMP,
    CONSTRAINT fk_atendimento_denuncia FOREIGN KEY (denuncia_id) REFERENCES issues(id) ON DELETE CASCADE,
    CONSTRAINT fk_atendimento_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id)
);

CREATE INDEX idx_atendimentos_empresa_status ON atendimentos_denuncia(empresa_id, status);
