CREATE TABLE arquivos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conteudo BYTEA NOT NULL,
    nome_original VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    tamanho_bytes BIGINT NOT NULL,
    data_criacao TIMESTAMP NOT NULL
);

ALTER TABLE pracas ADD COLUMN arquivo_id BIGINT;
ALTER TABLE issues ADD COLUMN arquivo_id BIGINT;
ALTER TABLE atendimentos_denuncia ADD COLUMN arquivo_id BIGINT;

INSERT INTO arquivos (id, conteudo, nome_original, content_type, tamanho_bytes, data_criacao)
SELECT -id, foto, COALESCE(foto_nome_original, 'praca-' || id || '.jpg'),
       COALESCE(foto_content_type, 'image/jpeg'), OCTET_LENGTH(foto), CURRENT_TIMESTAMP
FROM pracas
WHERE foto IS NOT NULL;

UPDATE pracas SET arquivo_id = -id WHERE foto IS NOT NULL;

ALTER TABLE pracas ADD CONSTRAINT fk_praca_arquivo FOREIGN KEY (arquivo_id) REFERENCES arquivos(id);
ALTER TABLE issues ADD CONSTRAINT fk_issue_arquivo FOREIGN KEY (arquivo_id) REFERENCES arquivos(id);
ALTER TABLE atendimentos_denuncia ADD CONSTRAINT fk_atendimento_arquivo FOREIGN KEY (arquivo_id) REFERENCES arquivos(id);

ALTER TABLE pracas DROP COLUMN foto_url;
ALTER TABLE pracas DROP COLUMN foto;
ALTER TABLE pracas DROP COLUMN foto_content_type;
ALTER TABLE pracas DROP COLUMN foto_nome_original;
ALTER TABLE issues DROP COLUMN foto_url;
ALTER TABLE atendimentos_denuncia DROP COLUMN foto_depois_url;
