CREATE TABLE usuarios
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      varchar(255),
    password      varchar(255),
    role          varchar(255),
    refresh_token varchar(512)
);